INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON ) VALUES (1000,'Complete the labs in JDG + EAP', 0, FALSE, '2014-08-20', NULL);
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON ) VALUES (1001,'Sell more JDG', 0, FALSE, '2014-08-20', NULL);
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON ) VALUES (1002,'Sell more EAP', 0, TRUE, '2014-08-20', '2014-08-31');
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON ) VALUES (1003,'Send feedback on the training to tqvarnst@redhat.com', 0, FALSE, '2014-08-20', NULL);
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON ) VALUES (1004,'Send feedback to sme-jdg to the developers how great JDG is', 0, FALSE, '2014-08-20', NULL);
