<<<<<<< HEAD
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON ) VALUES (10001,'Complete the labs in JDG + EAP', 0, FALSE, '2014-08-20', NULL);
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON ) VALUES (10002,'Sell more JDG', 0, FALSE, '2014-08-20', NULL);
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON ) VALUES (10003,'Sell more EAP', 0, TRUE, '2014-08-20', '2014-08-31');
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON ) VALUES (10004,'Send feedback on the training to tqvarnst@redhat.com', 0, FALSE, '2014-08-20', NULL);
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON ) VALUES (10005,'Send feedback to sme-jdg to the developers how great JDG is', 0, FALSE, '2014-08-20', NULL);

INSERT INTO USER ( USERNAME, VERSION ) VALUES ('defaultUser',0);

INSERT INTO USER_TASK (USER_USERNAME, TASKS_ID) VALUES ('defaultUser',10001);
INSERT INTO USER_TASK (USER_USERNAME, TASKS_ID) VALUES ('defaultUser',10002);
INSERT INTO USER_TASK (USER_USERNAME, TASKS_ID) VALUES ('defaultUser',10003);
INSERT INTO USER_TASK (USER_USERNAME, TASKS_ID) VALUES ('defaultUser',10004);
INSERT INTO USER_TASK (USER_USERNAME, TASKS_ID) VALUES ('defaultUser',10005);


