INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON ) VALUES (-1,'Complete the labs in JDG + EAP', 0, FALSE, '2014-08-20', NULL);
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON ) VALUES (-2,'Sell more JDG', 0, FALSE, '2014-08-20', NULL);
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON ) VALUES (-3,'Sell more EAP', 0, TRUE, '2014-08-20', '2014-08-31');
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON ) VALUES (-4,'Send feedback on the training to tqvarnst@redhat.com', 0, FALSE, '2014-08-20', NULL);
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON ) VALUES (-5,'Send feedback to sme-jdg to the developers how great JDG is', 0, FALSE, '2014-08-20', NULL);

INSERT INTO USER ( ID, VERSION ) VALUES (-1,0);

INSERT INTO USER_TASK (USER_ID, TASKS_ID) VALUES (-1,-1);
INSERT INTO USER_TASK (USER_ID, TASKS_ID) VALUES (-1,-2);
INSERT INTO USER_TASK (USER_ID, TASKS_ID) VALUES (-1,-3);
INSERT INTO USER_TASK (USER_ID, TASKS_ID) VALUES (-1,-4);
INSERT INTO USER_TASK (USER_ID, TASKS_ID) VALUES (-1,-5);


