INSERT INTO USER (USERNAME, VERSION) VALUES ('defaultUser',0);

INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON, OWNER_USERNAME ) VALUES (100001,'Complete the labs in JDG + EAP', 0, FALSE, '2014-08-20', NULL, 'defaultUser');
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON, OWNER_USERNAME ) VALUES (100002,'Sell more JDG', 0, FALSE, '2014-08-20', NULL, 'defaultUser');
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON, OWNER_USERNAME ) VALUES (100003,'Sell more EAP', 0, TRUE, '2014-08-20', '2014-08-31', 'defaultUser');
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON, OWNER_USERNAME ) VALUES (100004,'Send feedback on the training to tqvarnst@redhat.com', 0, FALSE, '2014-08-20', NULL, 'defaultUser');
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON, OWNER_USERNAME ) VALUES (100005,'Send feedback to sme-jdg to the developers how great JDG is', 0, FALSE, '2014-08-20', NULL, 'defaultUser');


