INSERT INTO USER (USERNAME, EMAIL, VERSION) VALUES ('johndoe','doe@redhat.com',0);
INSERT INTO USER (USERNAME, EMAIL, VERSION) VALUES ('janedoe','jane@redhat.com',0);
INSERT INTO USER (USERNAME, EMAIL, VERSION) VALUES ('johndoe2','doe@redhat.com',0);
INSERT INTO USER (USERNAME, EMAIL, VERSION) VALUES ('johndoe3','doe@redhat.com',0);
INSERT INTO USER (USERNAME, EMAIL, VERSION) VALUES ('arnold','arnlod@schwarzenegger.com',0);
INSERT INTO USER (USERNAME, EMAIL, VERSION) VALUES ('anakin','anakin@skywalker.com',0);
INSERT INTO USER (USERNAME, EMAIL, VERSION) VALUES ('han','han@solo.com',0);
INSERT INTO USER (USERNAME, EMAIL, VERSION) VALUES ('darth','darth@vader.com',0);
INSERT INTO USER (USERNAME, EMAIL, VERSION) VALUES ('obi','obiwan@kenobi.com',0);





INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON, OWNER_USERNAME ) VALUES (100001,'Complete the labs in JDG + EAP', 0, FALSE, '2014-08-20', NULL, 'johndoe');
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON, OWNER_USERNAME ) VALUES (100002,'Sell more JDG', 0, FALSE, '2014-08-20', NULL, 'johndoe');
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON, OWNER_USERNAME ) VALUES (100003,'Sell more EAP', 0, TRUE, '2014-08-20', '2014-08-31', 'johndoe');
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON, OWNER_USERNAME ) VALUES (100004,'Send feedback on the training to tqvarnst@redhat.com', 0, FALSE, '2014-08-20', NULL, 'johndoe');
INSERT INTO TASK ( ID , TITLE  , VERSION, DONE , CREATEDON , COMPLETEDON, OWNER_USERNAME ) VALUES (100005,'Send feedback to sme-jdg to the developers how great JDG is', 0, FALSE, '2014-08-20', NULL, 'johndoe');


